
<div class="container-fluid">

<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800"></h1>
        
</div>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <table width="100%" style="font-family: sans-serif;" cellpadding="10">
        <tr>
            <td width="100%" style="text-align: center; font-size: 20px; font-weight: bold; padding: 0px;">
             Available Rooms Report
            </td><br>
        </tr>
    </table>
    <table width="100%" style="font-family: sans-serif;" cellpadding="10">
        <tr>
            <td width="49%" style="text-align: left;"><strong>Hotel Grand Opera</strong><br>Mirigama<br>Sri Lanka<br>0332275096</td>

            <td width="2%">&nbsp;</td>
            <td width="49%" style="text-align: right;"><br><strong>Generated By:</strong> {{ Auth::user()->fname }} {{ Auth::user()->lname }}<br><strong>Generated Date/Time:</strong> <?php echo(strftime("%m/%d/%Y %H:%M")); ?></td><br>
        </tr>
    </table>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="example1" width="100%" cellspacing="0" style="border: 0.1mm solid #eee;">

      <thead style="background-color:#F5F5F5; border: 0.1mm solid #eee;">
                    <tr style="color:black;">
                                <th></th>
                                <th>Room Type</th>
                                <th>Room Facilities</th>
                                <th>Room No</th>
                                <th>Availability</th>
                                <th>Create Date</th>
                    </tr>
                  </thead>
                       @foreach($rooms as $value)
                              <tr>
                                <td></td>
                                <td style="border: 0.1mm solid #eee;">{{$value->type_name}}</td>
                                <td style="border: 0.1mm solid #eee;">{{$value->facilities}}</td>
                                <td style="border: 0.1mm solid #eee;">{{$value->room_no}}</td>
                                <td>  @if ($value->status == 1)
                                <span class="badge badge-success">Available</span>
                                 @elseif ($value->status == 0)
                                <span class="badge badge-danger">Not Available</span>
                                @else
                                @endif
                                </td>
                                <td style="border: 0.1mm solid #eee;">{{ \Carbon\Carbon::parse($value->created_at)->format('d/m/Y H:i:s A')}}</td>
                                

                  </tr>
                  @endforeach
                  <h4 style="color:red; text-align: right;">{{ \DB::table('rooms')->where('rooms.status', '=' , 1)->count()}} Rooms on Report</h4>
                  </tbody><br><br><br>
                </table>
                </div>
            </div>
            </div>
          </div>

        </div>

